[project]
name = 'deorganized-gaming-onchain'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.ttt-v01]
path = 'contracts/ttt-v01.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
